[package]
name = "tile"
version = "0.1.0"
authors = ["Yufeng Wang <yufengwang05@gmail.com>"]
edition = "2021"

[workspace]
members = [
  "tllang",
  "tlmito",
  "tlrepl",
]

[dependencies]
clap = { version = "3.1", features = ["derive"] }
tlrepl = { path = "tlrepl" }
